version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - '5000:5000'
    command: tail -f /dev/null
    environment:
      - APP_NAME=auth-plus
      - APP_PORT=5000
      - NODE_ENV=development
      - DBMATE_DATABASE_URL=postgres://root:root@database:5432/auth?sslmode=disable
      - DBMATE_WAIT_TIMEOUT=60s
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_DATABASE=auth
      - DATABASE_PORT=5432
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    volumes:
      - .:/app
    restart: always
    networks:
      - host
    depends_on:
      - database
      - cache

  database:
    image: postgres:11.12
    restart: always
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'auth'
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - host

  cache:
    image: redis:6.2.4
    hostname: redis
    restart: always
    volumes:
      - v-cache:/data
    ports:
      - '6379:6379'
    networks:
      - host

  cache-ui:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=local:redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dummy
    ports:
      - '8081:8081'
    depends_on:
      - cache
    networks:
      - host

networks:
  host:
    driver: bridge

volumes:
  v-database:
  v-cache:
