version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
      labels:
        - ${APP_NAME}:development
    ports:
      - '5000:5000'
    command: tail -f /dev/null
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - host
    depends_on:
      - database

  database:
    image: postgres:11.12
    restart: always
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'auth'
    ports:
      - '5432:5432'
    volumes:
      - my-db:/var/lib/postgres
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - host

networks:
  host:

volumes:
  my-db:
