version: '3.3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - '5000:5000'
    command: tail -f /dev/null
    environment:
      - APP_NAME=auth-plus-main
      - PORT=5000
      - NODE_ENV=development
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_DATABASE=auth
      - DATABASE_PORT=5432
      - CACHE_HOST=redis
      - CACHE_PORT=6379
    volumes:
      - .:/app
    restart: always
    networks:
      - host
    depends_on:
      - database
      - cache

  database:
    image: postgres:11.12
    restart: always
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'auth'
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - host

  database-migration:
    image: amacneil/dbmate
    command: --url postgres://root:root@database:5432/auth?sslmode=disable --wait --wait-timeout 60s up
    volumes:
      - ./db:/db
    depends_on:
      - database
    networks:
      - host

  cache:
    image: redis:6.2.4
    hostname: redis
    restart: always
    volumes:
      - v-cache:/data
    ports:
      - '6379:6379'
    networks:
      - host

  cache-ui:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=local:redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=dummy
    ports:
      - '8081:8081'
    depends_on:
      - cache
    networks:
      - host

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.29.1
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - v-metrics:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml 
    networks:
      - host
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  grafana:
    container_name: grafana
    image: grafana/grafana:8.1.2
    restart: always
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - host

networks:
  host:
    driver: bridge
  

volumes:
  v-database:
  v-cache:
  v-metrics:
