version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - '5000:5000'
    command: tail -f /dev/null
    environment:
      - APP_NAME=auth-plus-authentication
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=dPBZ_CSWBApK&7EwL?!_%5dLjTK7An
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=db_password
      - DATABASE_DATABASE=auth
      - DATABASE_PORT=5432
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - LOGSTASH_HOST=elasticsearch
      - LOGSTASH_PORT=5044
      - KAFKA_HOST=kafka
      - KAFKA_PORT=29092
    volumes:
      - .:/app
    restart: always
    networks:
      - authentication-net
    depends_on:
      - database
      - cache

  database:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: auth
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
    networks:
      - authentication-net

  cache:
    container_name: redis
    image: redis:7.0.5
    hostname: redis
    restart: always
    volumes:
      - v-cache:/data
    ports:
      - '6379:6379'
    networks:
      - authentication-net

  cache-ui:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8081:8081'
    depends_on:
      - cache
    networks:
      - authentication-net

networks:
  authentication-net:
    driver: bridge

volumes:
  v-database:
  v-cache:
