version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - "5000:5000"
    command: tail -f /dev/null
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-mgr
    hostname: rabbitmq-mgr
    ports:
      - "8080:15672"