version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency
    ports:
      - "5000:5000"
    command: tail -f /dev/null
    volumes:
      - .:/app
      - ./node_modules
    restart: always
  kafka:
    image: kafkamanager/kafka-manager
    restart: always
    environment:
      - eZK_HOSTS=127.0.0.2
