service: backend-main
runtime: nodejs14
instance_class: F1

env_variables:
  APP_NAME: auth-plus-main
  DATABASE_HOST: database
  DATABASE_USER: postgres
  DATABASE_PASSWORD: 9scey1jwtHiOncjA
  DATABASE_DATABASE: auth
  DATABASE_PORT: 5432
  CACHE_HOST: redis
  CACHE_PORT: 6379

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto