apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-main
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: api:0.0.1
        ports:
        - containerPort: 80