name: Continuous Delivery on Merge
on:
  push:
    branches: master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use right version of node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@auth-plus'
      - name: Install dependencies
        run: npm ci
      - name: Verify build
        run: npm run build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Trigger GCP Cloud Build
        run: gcloud builds submit gcloud builds submit --config cloudbuild.yaml ./src
