name: Continuous Integration on Pull Request
on:
  pull_request:
    branches: [staging, master]
    
jobs:
  Audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use right version of node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Verify vulnerabilities
        run: npm audit
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Execute test
        run: make test/ci
      - name: create sonarcloud file
        run: |
          echo "sonar.projectKey=AndrewHanasiro_auth-plus" >> $HOME/sonar-project.properties
          echo "sonar.organization=auth-plus" >> $HOME/sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=./coverage/lcov.info" >> $HOME/sonar-project.properties
          echo "sonar.sources=./src" >> $HOME/sonar-project.properties
          echo "sonar.tests=./test" >> $HOME/sonar-project.properties
          echo "sonar.language=js" >> $HOME/sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> $HOME/sonar-project.properties
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
          files: ./coverage/cobertura-coverage.xml
      - name: Test & publish to Code Climate
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
          coverageCommand: echo 'test already done'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/cobertura-coverage.xml
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Verify build
        run: npm run build -- --noEmit
