name: Continuous Delivery on Merge
on:
  push:
    branches: master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use right version of node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Create a .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGE_TOKEN }}" >> .npmrc
          echo "@auth-plus:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Copy GCP config files
        run: |
          cp ./config/cloudbuild.yaml ./cloudbuild.yaml
          cp ./config/dispatch.yaml ./dispatch.yaml
          cp ./config/app.yaml ./app.yaml
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/auth-plus-backend-main:$GITHUB_SHA"
