name: Continuous Delivery on Merge
on:
  push:
    branches: master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use right version of node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Verify vulnerabilities
        run: npm audit
      - name: Execute test
        run: npm test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
          files: ./coverage/cobertura-coverage.xml
      - name: Test & publish to Code Climate
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
          coverageCommand: npm run test
      - name: Verify build
        run: npm run build
