name: Continous Integration on Pull Request
on:
  pull_request:
    branches: [staging, master]
jobs:
  Audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use right version of node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Verify vulnerabilities
        run: npm audit
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Execute test
        run: npm test
      - name: Create a file to sonar cloud
        run: cat > sonar-project.properties << EOF
          sonar.organization=andrewhanasiro
          sonar.projectKey=AndrewHanasiro_auth-plus
          sonar.javascript.lcov.reportPaths=coverage/lcov.info
          sonar.sources=src/
          sonar.test.exclusions=tests/**
          sonar.tests=test/
          sonar.verbose=true
          EOF
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install dependencies
        run: npm ci
      - name: Verify build
        run: npm run build
